"""
Куровані набори слів з популярних пісень — для швидкого старту вивчення.
Ключ — target_lang (мова, яку юзер вивчає).

Підбірка балансу: ~10 паків на мову, 10-12 слів кожний. Слова — переважно
з buttom 1000 lemma frequency target-мови, зустрічаються у щоденних розмовах
і у пісні мають впізнаваний контекст.
"""

SONG_PACKS = {
    "en": [
        {
            "id": "en-imagine",
            "title": "Imagine",
            "artist": "John Lennon",
            "emoji": "🕊️",
            "words": ["imagine", "heaven", "peace", "dreamer", "brotherhood",
                      "possessions", "share", "join", "above", "below"],
        },
        {
            "id": "en-hello",
            "title": "Hello",
            "artist": "Adele",
            "emoji": "📞",
            "words": ["wonder", "outside", "calling", "thousand",
                      "tear apart", "regret", "at least", "different",
                      "anymore", "matter"],
        },
        {
            "id": "en-yesterday",
            "title": "Yesterday",
            "artist": "The Beatles",
            "emoji": "🌅",
            "words": ["yesterday", "trouble", "far away", "shadow",
                      "suddenly", "believe", "hide", "wrong", "stay", "say"],
        },
        {
            "id": "en-perfect",
            "title": "Perfect",
            "artist": "Ed Sheeran",
            "emoji": "💕",
            "words": ["perfect", "darling", "sweetheart", "underneath",
                      "barefoot", "stranger", "carry", "whisper",
                      "follow", "lead"],
        },
        {
            "id": "en-shape-of-you",
            "title": "Shape of You",
            "artist": "Ed Sheeran",
            "emoji": "💃",
            "words": ["body", "shape", "discover", "quick", "handmade",
                      "share", "couple", "drink", "follow", "fall in love"],
        },
        {
            "id": "en-someone-like-you",
            "title": "Someone Like You",
            "artist": "Adele",
            "emoji": "💔",
            "words": ["settle down", "bother", "uninvited", "memories",
                      "begged", "instead", "old friend", "ahead",
                      "regret", "ago"],
        },
        {
            "id": "en-bohemian",
            "title": "Bohemian Rhapsody",
            "artist": "Queen",
            "emoji": "🎭",
            "words": ["nothing matters", "reality", "fantasy", "escape",
                      "trigger", "thunderbolt", "frighten", "easy come",
                      "spare", "let me go"],
        },
        {
            "id": "en-hallelujah",
            "title": "Hallelujah",
            "artist": "Leonard Cohen",
            "emoji": "🕯️",
            "words": ["secret", "chord", "please", "broken", "halt",
                      "kitchen chair", "throne", "overthrew", "hallelujah",
                      "remind"],
        },
        {
            "id": "en-let-it-be",
            "title": "Let It Be",
            "artist": "The Beatles",
            "emoji": "🌿",
            "words": ["mother", "trouble", "wisdom", "darkness", "stand",
                      "answer", "let it be", "hour", "broken-hearted",
                      "agreement"],
        },
        {
            "id": "en-shallow",
            "title": "Shallow",
            "artist": "Lady Gaga",
            "emoji": "🌊",
            "words": ["shallow", "dive", "crash", "off the deep end",
                      "happy", "modern", "old ways", "noise", "afraid",
                      "change"],
        },
        {
            "id": "en-take-me-to-church",
            "title": "Take Me to Church",
            "artist": "Hozier",
            "emoji": "⛪",
            "words": ["worship", "lover", "lie", "command", "deathless",
                      "starve", "earthly", "sin", "heaven", "knife"],
        },
        {
            "id": "en-photograph",
            "title": "Photograph",
            "artist": "Ed Sheeran",
            "emoji": "📷",
            "words": ["photograph", "loving", "hurt", "memory", "frozen",
                      "souvenir", "necklace", "underneath", "wait for me",
                      "come home"],
        },
    ],
    "es": [
        {
            "id": "es-despacito",
            "title": "Despacito",
            "artist": "Luis Fonsi",
            "emoji": "💃",
            "words": ["despacito", "suavecito", "respiro", "lentamente",
                      "abrazo", "firmar", "rincón", "labio", "oído",
                      "pasito"],
        },
        {
            "id": "es-vivir",
            "title": "Vivir Mi Vida",
            "artist": "Marc Anthony",
            "emoji": "🌞",
            "words": ["vivir", "reír", "celebrar", "llorar", "soñar",
                      "agradecer", "camino", "alegría", "valor", "momento"],
        },
        {
            "id": "es-bailando",
            "title": "Bailando",
            "artist": "Enrique Iglesias",
            "emoji": "🕺",
            "words": ["bailar", "ritmo", "corazón", "abrazar",
                      "lentamente", "respirar", "olvidar", "sentir",
                      "perder", "encontrar"],
        },
        {
            "id": "es-besame",
            "title": "Bésame Mucho",
            "artist": "Consuelo Velázquez",
            "emoji": "💋",
            "words": ["besar", "mucho", "noche", "miedo", "perder",
                      "después", "lejos", "cerca", "junto a ti", "vida mía"],
        },
        {
            "id": "es-hijo-luna",
            "title": "Hijo de la Luna",
            "artist": "Mecano",
            "emoji": "🌙",
            "words": ["luna", "gitano", "moreno", "padre", "hijo",
                      "promesa", "cuna", "ojos", "mecer", "cielo"],
        },
        {
            "id": "es-corazon-espinado",
            "title": "Corazón Espinado",
            "artist": "Santana",
            "emoji": "❤️‍🩹",
            "words": ["espina", "lastimar", "olvidar", "engaño", "desengaño",
                      "mujer", "amargura", "soledad", "ternura", "pedazo"],
        },
        {
            "id": "es-quizas",
            "title": "Quizás, Quizás, Quizás",
            "artist": "Osvaldo Farrés",
            "emoji": "🤔",
            "words": ["quizás", "preguntar", "tiempo", "perder", "manera",
                      "siempre", "responder", "decidir", "duda", "cansado"],
        },
        {
            "id": "es-vida-carnaval",
            "title": "La Vida Es Un Carnaval",
            "artist": "Celia Cruz",
            "emoji": "✨",
            "words": ["vida", "carnaval", "sufrir", "cantar", "vivir",
                      "ay", "sufrimiento", "alegre", "esperar", "sonreír"],
        },
        {
            "id": "es-macarena",
            "title": "Macarena",
            "artist": "Los del Río",
            "emoji": "🎉",
            "words": ["fiesta", "amiga", "cuerpo", "alegría", "novio",
                      "verano", "marcharse", "hacer", "cosa", "llamar"],
        },
        {
            "id": "es-ojala",
            "title": "Ojalá",
            "artist": "Silvio Rodríguez",
            "emoji": "🌾",
            "words": ["ojalá", "lluvia", "olvidar", "palabra", "mirada",
                      "siempre", "pasar", "manera", "permitir", "sin ti"],
        },
    ],
    "pl": [
        {
            "id": "pl-kasztany",
            "title": "Kasztany",
            "artist": "Maciej Maleńczuk",
            "emoji": "🌰",
            "words": ["kasztan", "spadać", "jesień", "dziewczyna",
                      "spojrzenie", "wspomnienie", "wracać", "tęsknota",
                      "ulica", "park"],
        },
        {
            "id": "pl-warszawa",
            "title": "Warszawa",
            "artist": "T.Love",
            "emoji": "🏙️",
            "words": ["miasto", "ulica", "świt", "tańczyć",
                      "pamiętać", "wiosna", "deszcz", "noc",
                      "przyjaciel", "chodzić"],
        },
        {
            "id": "pl-szczescie",
            "title": "Małe Szczęścia",
            "artist": "Sylwia Grzeszczak",
            "emoji": "✨",
            "words": ["szczęście", "uśmiech", "drobny", "uwierzyć",
                      "marzenie", "spokój", "radość", "chwila",
                      "odnaleźć", "codzienność"],
        },
        {
            "id": "pl-malgoska",
            "title": "Małgośka",
            "artist": "Maryla Rodowicz",
            "emoji": "👧",
            "words": ["facet", "wart", "łzy", "kochać", "kłamać",
                      "wstyd", "powtarzać", "przyjaciółka", "chłopak",
                      "kłótnia"],
        },
        {
            "id": "pl-sen-warszawie",
            "title": "Sen o Warszawie",
            "artist": "Czesław Niemen",
            "emoji": "🌃",
            "words": ["sen", "miasto", "śnić", "ulica", "rzeka",
                      "świat", "wracać", "szukać", "kochany", "bliski"],
        },
        {
            "id": "pl-niepokonani",
            "title": "Niepokonani",
            "artist": "Edyta Bartosiewicz",
            "emoji": "💪",
            "words": ["niepokonany", "walka", "siła", "wiara", "upadać",
                      "wstać", "razem", "marzyć", "iść dalej", "nadzieja"],
        },
        {
            "id": "pl-sztorm",
            "title": "Sztorm",
            "artist": "Kasia Nosowska",
            "emoji": "🌊",
            "words": ["sztorm", "fala", "morze", "burza", "spokojny",
                      "tracić", "ratować", "brzeg", "wiatr", "zostać"],
        },
        {
            "id": "pl-modlitwa",
            "title": "Modlitwa",
            "artist": "Halina Frąckowiak",
            "emoji": "🙏",
            "words": ["modlić się", "prośba", "łaska", "anioł", "łza",
                      "wybaczyć", "winowajca", "spokój", "duszę", "chronić"],
        },
        {
            "id": "pl-cala-sala",
            "title": "Cała sala śpiewa z nami",
            "artist": "Sztywny Pal Azji",
            "emoji": "🎤",
            "words": ["sala", "śpiewać", "głośno", "razem", "balet",
                      "kolega", "wesele", "tańczyć", "zabawa", "klaskać"],
        },
        {
            "id": "pl-jolka",
            "title": "Jolka, Jolka pamiętasz",
            "artist": "Budka Suflera",
            "emoji": "💔",
            "words": ["pamiętać", "lato", "miłość", "rozstanie", "obietnica",
                      "wiara", "list", "czekać", "wspominać", "samotny"],
        },
    ],
    "de": [
        {
            "id": "de-99",
            "title": "99 Luftballons",
            "artist": "Nena",
            "emoji": "🎈",
            "words": ["Luftballon", "Horizont", "Krieg", "Frieden",
                      "Soldat", "Pilot", "Feuerwerk", "verlieren",
                      "Nachbar", "fliegen"],
        },
        {
            "id": "de-atemlos",
            "title": "Atemlos durch die Nacht",
            "artist": "Helene Fischer",
            "emoji": "🌙",
            "words": ["atemlos", "Herz", "Gefühl", "Sehnsucht",
                      "fliegen", "wachsen", "ewig", "still",
                      "Nacht", "Wahnsinn"],
        },
        {
            "id": "de-uber-den-wolken",
            "title": "Über den Wolken",
            "artist": "Reinhard Mey",
            "emoji": "☁️",
            "words": ["Wolke", "grenzenlos", "Freiheit", "Sorge",
                      "Angst", "klein", "Erde", "Traum",
                      "Flughafen", "Regen"],
        },
        {
            "id": "de-stadt",
            "title": "Stadt",
            "artist": "Cassandra Steen & Adel Tawil",
            "emoji": "🌆",
            "words": ["Stadt", "bauen", "Mauer", "Liebe", "Mensch",
                      "Hoffnung", "verlieren", "verändern", "Ziel", "Mut"],
        },
        {
            "id": "de-schrei-nach-liebe",
            "title": "Schrei nach Liebe",
            "artist": "Die Ärzte",
            "emoji": "💔",
            "words": ["schreien", "Liebe", "Hass", "schlagen", "treten",
                      "verstehen", "Schwäche", "Mitleid", "Verlierer",
                      "Arschloch"],
        },
        {
            "id": "de-ein-kompliment",
            "title": "Ein Kompliment",
            "artist": "Sportfreunde Stiller",
            "emoji": "😊",
            "words": ["Kompliment", "Augen", "Lächeln", "schenken",
                      "leuchten", "fühlen", "warm", "lachen", "ehrlich",
                      "lieben"],
        },
        {
            "id": "de-lemon-tree",
            "title": "Lemon Tree",
            "artist": "Fools Garden",
            "emoji": "🍋",
            "words": ["Zitrone", "Baum", "warten", "langweilig", "Sonne",
                      "Schatten", "blau", "Einsamkeit", "Spaziergang",
                      "Auto"],
        },
        {
            "id": "de-major-tom",
            "title": "Major Tom",
            "artist": "Peter Schilling",
            "emoji": "🚀",
            "words": ["Rakete", "Erde", "Weltraum", "Stille", "Triebwerk",
                      "Kontrolle", "Abschied", "schweben", "fern", "leise"],
        },
        {
            "id": "de-auf-uns",
            "title": "Auf uns",
            "artist": "Andreas Bourani",
            "emoji": "🥂",
            "words": ["anstoßen", "Freund", "Glück", "Augenblick",
                      "Ewigkeit", "Lebensgefühl", "wagen", "tanzen",
                      "feiern", "leben"],
        },
        {
            "id": "de-der-weg",
            "title": "Der Weg",
            "artist": "Herbert Grönemeyer",
            "emoji": "🛣️",
            "words": ["Weg", "Schritt", "weiter", "stark", "Sturm",
                      "tragen", "leise", "verlassen", "Last", "Ziel"],
        },
    ],
    "uk": [
        {
            "id": "uk-chervona-ruta",
            "title": "Червона рута",
            "artist": "Володимир Івасюк",
            "emoji": "🌹",
            "words": ["рута", "знайти", "вечір", "очі",
                      "любов", "квіти", "серце", "обличчя",
                      "сон", "стежка"],
        },
        {
            "id": "uk-vse-bude-dobre",
            "title": "Все буде добре",
            "artist": "Океан Ельзи",
            "emoji": "🌅",
            "words": ["вірити", "дочекатись", "сонце", "небо",
                      "майбутнє", "обійми", "шлях", "тримайся",
                      "поруч", "перемагати"],
        },
        {
            "id": "uk-okean",
            "title": "Така як ти",
            "artist": "Океан Ельзи",
            "emoji": "💜",
            "words": ["погляд", "ніжність", "посмішка", "доля",
                      "вірність", "тиша", "знову", "плече",
                      "минати", "дотик"],
        },
        {
            "id": "uk-stina",
            "title": "Стіна",
            "artist": "Океан Ельзи",
            "emoji": "🧱",
            "words": ["стіна", "будувати", "руйнувати", "тиша",
                      "крик", "втрата", "повернутись", "пам'ятати",
                      "відпустити", "сумніватися"],
        },
        {
            "id": "uk-ne-tvoya-viyna",
            "title": "Не твоя війна",
            "artist": "Океан Ельзи",
            "emoji": "🕊️",
            "words": ["війна", "брат", "земля", "молитва", "серце",
                      "захищати", "ніч", "спалити", "чути", "впасти"],
        },
        {
            "id": "uk-svitlo",
            "title": "Світло",
            "artist": "KAZKA",
            "emoji": "✨",
            "words": ["світло", "темрява", "знайти", "втратити",
                      "торкнутись", "тримати", "вірити", "падати",
                      "піднятись", "разом"],
        },
        {
            "id": "uk-plakala",
            "title": "Плакала",
            "artist": "KAZKA",
            "emoji": "😢",
            "words": ["плакати", "сльоза", "зрадити", "брехати",
                      "забути", "дитина", "матір", "співати",
                      "колискова", "дівчинка"],
        },
        {
            "id": "uk-vyshche-neba",
            "title": "Вище неба",
            "artist": "Тіна Кароль",
            "emoji": "☁️",
            "words": ["вище", "небо", "крила", "політ",
                      "хмара", "падати", "тримати", "довіряти",
                      "вільний", "далечінь"],
        },
        {
            "id": "uk-1944",
            "title": "1944",
            "artist": "Jamala",
            "emoji": "✊",
            "words": ["чужий", "прийти", "забрати", "життя",
                      "ніч", "молитва", "пам'ять", "людство",
                      "знищити", "повернення"],
        },
        {
            "id": "uk-perevaal",
            "title": "Перевал",
            "artist": "Володимир Івасюк",
            "emoji": "🌄",
            "words": ["перевал", "гори", "стежка", "крик",
                      "відлуння", "верхів'я", "хмара", "смерека",
                      "блукати", "далекий"],
        },
    ],
}


def get_packs(target_lang: str) -> list:
    return SONG_PACKS.get(target_lang, [])


def get_pack(target_lang: str, pack_id: str) -> dict | None:
    for p in SONG_PACKS.get(target_lang, []):
        if p["id"] == pack_id:
            return p
    return None
