"""
Тематичні набори лексики для типових життєвих ситуацій діаспори:
бюрократія, медицина, оренда, банк, робота, школа.

На відміну від song_packs — це не "цікавий контекст", а інструментальна
лексика яка реально потрібна коли треба заповнити форму, поговорити з
лікарем, відкрити рахунок. Курована, ~10 слів на тему.

Ключ — target_lang.
"""

THEME_PACKS = {
    "de": [
        {
            "id": "de-buergeramt",
            "title": "Bürgeramt",
            "artist": "Реєстрація · документи",
            "emoji": "🏢",
            "words": ["Anmeldung", "Termin", "Wartenummer",
                      "Meldebescheinigung", "Personalausweis",
                      "Reisepass", "unterschreiben", "Formular",
                      "Sachbearbeiter", "Hauptwohnsitz"],
        },
        {
            "id": "de-arzt",
            "title": "Beim Arzt",
            "artist": "Лікар · страхування",
            "emoji": "🩺",
            "words": ["Termin vereinbaren", "Hausarzt",
                      "Krankenversicherung", "Versicherungskarte",
                      "Rezept", "Überweisung", "Beschwerden",
                      "Allergie", "Krankschreibung", "Apotheke"],
        },
        {
            "id": "de-mietvertrag",
            "title": "Mietvertrag",
            "artist": "Оренда житла",
            "emoji": "🏠",
            "words": ["Kaution", "Miete", "Nebenkosten", "Wohnung",
                      "Vermieter", "Kündigungsfrist",
                      "Schlüsselübergabe", "Übergabeprotokoll",
                      "Heizung", "Hausordnung"],
        },
        {
            "id": "de-bank",
            "title": "Bank",
            "artist": "Рахунок · перекази",
            "emoji": "🏦",
            "words": ["Konto eröffnen", "Girokonto", "Überweisung",
                      "IBAN", "Dauerauftrag", "Lastschrift",
                      "Kontoauszug", "Geldautomat", "Kreditkarte",
                      "Überziehungslimit"],
        },
        {
            "id": "de-bewerbung",
            "title": "Bewerbung",
            "artist": "Робота · інтерв'ю",
            "emoji": "💼",
            "words": ["Lebenslauf", "Anschreiben",
                      "Vorstellungsgespräch", "Probezeit",
                      "Arbeitsvertrag", "Gehalt", "Vollzeit",
                      "Teilzeit", "Urlaubstage", "Kündigungsfrist"],
        },
        {
            "id": "de-schule",
            "title": "Schule & Kita",
            "artist": "Школа · діти",
            "emoji": "🎒",
            "words": ["Schulanmeldung", "Klassenlehrer",
                      "Hausaufgaben", "Stundenplan", "Elternabend",
                      "Zeugnis", "Ferien", "Mensa", "Kita",
                      "Schulpflicht"],
        },
    ],
    "pl": [
        {
            "id": "pl-urzad",
            "title": "W urzędzie",
            "artist": "PESEL · karta pobytu",
            "emoji": "🏛️",
            "words": ["urząd", "meldunek", "PESEL", "karta pobytu",
                      "wniosek", "formularz", "termin", "kolejka",
                      "podpisać", "urzędnik"],
        },
        {
            "id": "pl-lekarz",
            "title": "U lekarza",
            "artist": "NFZ · apteka",
            "emoji": "🩺",
            "words": ["lekarz rodzinny", "przychodnia", "recepta",
                      "skierowanie", "objawy", "alergia",
                      "ubezpieczenie zdrowotne", "NFZ", "apteka",
                      "zwolnienie lekarskie"],
        },
        {
            "id": "pl-mieszkanie",
            "title": "Mieszkanie",
            "artist": "Оренда · опати",
            "emoji": "🏠",
            "words": ["wynajem", "kaucja", "czynsz", "opłaty",
                      "umowa najmu", "właściciel", "najemca",
                      "klucze", "ogrzewanie", "remont"],
        },
        {
            "id": "pl-bank",
            "title": "Bank",
            "artist": "Konto · BLIK · przelew",
            "emoji": "🏦",
            "words": ["konto", "karta płatnicza", "przelew",
                      "bankomat", "wypłata", "saldo", "IBAN",
                      "BLIK", "kredyt", "prowizja"],
        },
        {
            "id": "pl-praca",
            "title": "Praca",
            "artist": "Umowa · pensja",
            "emoji": "💼",
            "words": ["CV", "rozmowa kwalifikacyjna",
                      "umowa o pracę", "okres próbny", "pensja",
                      "urlop", "nadgodziny", "pełny etat",
                      "wypowiedzenie", "stawka godzinowa"],
        },
        {
            "id": "pl-szkola",
            "title": "Szkoła",
            "artist": "Дитина в школі",
            "emoji": "🎒",
            "words": ["szkoła", "klasa", "uczeń", "nauczyciel",
                      "lekcja", "praca domowa", "przedszkole",
                      "świadectwo", "wakacje", "stołówka"],
        },
    ],
    "es": [
        {
            "id": "es-empadronamiento",
            "title": "Empadronamiento",
            "artist": "NIE · ayuntamiento",
            "emoji": "🏛️",
            "words": ["empadronamiento", "ayuntamiento", "NIE",
                      "DNI", "cita previa", "formulario",
                      "justificante", "domicilio", "firma",
                      "residente"],
        },
        {
            "id": "es-medico",
            "title": "Médico",
            "artist": "Sanidad · farmacia",
            "emoji": "🩺",
            "words": ["médico de cabecera", "centro de salud",
                      "receta", "síntoma", "dolor", "alergia",
                      "seguro médico", "tarjeta sanitaria",
                      "farmacia", "urgencias"],
        },
        {
            "id": "es-alquiler",
            "title": "Alquiler de piso",
            "artist": "Fianza · contrato",
            "emoji": "🏠",
            "words": ["alquiler", "piso", "fianza",
                      "contrato de alquiler", "propietario",
                      "inquilino", "mensualidad", "gastos",
                      "comunidad", "llaves"],
        },
        {
            "id": "es-banco",
            "title": "Banco",
            "artist": "Cuenta · transferencia",
            "emoji": "🏦",
            "words": ["cuenta bancaria", "abrir cuenta", "tarjeta",
                      "transferencia", "ingresar", "retirar",
                      "saldo", "cajero automático", "domiciliar",
                      "comisión"],
        },
        {
            "id": "es-trabajo",
            "title": "Trabajo",
            "artist": "Entrevista · contrato",
            "emoji": "💼",
            "words": ["entrevista", "currículum", "contrato",
                      "nómina", "período de prueba", "horario",
                      "jornada completa", "vacaciones", "despido",
                      "sueldo bruto"],
        },
        {
            "id": "es-mercado",
            "title": "Supermercado",
            "artist": "Покупки",
            "emoji": "🛒",
            "words": ["supermercado", "carnicería", "panadería",
                      "frutería", "caja", "ofertas",
                      "fecha de caducidad", "precio", "recibo",
                      "bolsa de plástico"],
        },
    ],
    "en": [
        {
            "id": "en-immigration",
            "title": "Immigration",
            "artist": "Visa · residency",
            "emoji": "🛂",
            "words": ["visa", "residency permit", "naturalization",
                      "citizenship", "application form",
                      "biometrics appointment",
                      "supporting documents", "proof of address",
                      "expiration date", "renewal"],
        },
        {
            "id": "en-doctor",
            "title": "Doctor",
            "artist": "Healthcare · pharmacy",
            "emoji": "🩺",
            "words": ["appointment", "general practitioner",
                      "prescription", "referral", "symptoms",
                      "allergic reaction", "health insurance",
                      "pharmacy", "emergency room",
                      "doctor's note"],
        },
        {
            "id": "en-renting",
            "title": "Renting",
            "artist": "Lease · deposit",
            "emoji": "🏠",
            "words": ["lease", "security deposit", "monthly rent",
                      "landlord", "tenant", "utilities",
                      "maintenance request", "move-in date",
                      "eviction notice", "co-signer"],
        },
        {
            "id": "en-banking",
            "title": "Banking",
            "artist": "Account · transfers",
            "emoji": "🏦",
            "words": ["checking account", "savings account",
                      "direct deposit", "wire transfer", "balance",
                      "routing number", "ATM withdrawal",
                      "credit card", "overdraft", "bank statement"],
        },
        {
            "id": "en-job-interview",
            "title": "Job interview",
            "artist": "Resume · offer",
            "emoji": "💼",
            "words": ["resume", "cover letter", "interview",
                      "offer letter", "salary negotiation",
                      "benefits package", "probation period",
                      "onboarding", "references", "paid time off"],
        },
        {
            "id": "en-school",
            "title": "School",
            "artist": "Дитина в школі",
            "emoji": "🎒",
            "words": ["enroll", "principal",
                      "parent-teacher conference", "report card",
                      "homework", "field trip",
                      "after-school program", "school district",
                      "attendance", "tuition"],
        },
    ],
    "fr": [
        {
            "id": "fr-prefecture",
            "title": "Préfecture",
            "artist": "Titre de séjour · visa",
            "emoji": "🏛️",
            "words": ["préfecture", "titre de séjour",
                      "carte de séjour", "rendez-vous",
                      "récépissé", "justificatif de domicile",
                      "pièce d'identité", "dossier", "renouvellement",
                      "guichet"],
        },
        {
            "id": "fr-medecin",
            "title": "Chez le médecin",
            "artist": "Sécu · pharmacie",
            "emoji": "🩺",
            "words": ["médecin traitant", "ordonnance",
                      "carte vitale", "mutuelle", "symptômes",
                      "douleur", "allergie", "pharmacie",
                      "arrêt de travail", "remboursement"],
        },
        {
            "id": "fr-bail",
            "title": "Bail · location",
            "artist": "Caution · loyer",
            "emoji": "🏠",
            "words": ["bail", "loyer", "caution", "état des lieux",
                      "quittance de loyer", "propriétaire",
                      "locataire", "charges", "préavis",
                      "garant"],
        },
        {
            "id": "fr-banque",
            "title": "Banque",
            "artist": "Compte · virement · RIB",
            "emoji": "🏦",
            "words": ["compte courant", "ouvrir un compte", "RIB",
                      "virement", "prélèvement automatique",
                      "carte bancaire", "découvert", "relevé",
                      "distributeur", "agios"],
        },
        {
            "id": "fr-candidature",
            "title": "Candidature",
            "artist": "CV · CDI · entretien",
            "emoji": "💼",
            "words": ["CV", "lettre de motivation", "entretien",
                      "CDI", "CDD", "période d'essai", "salaire net",
                      "congés payés", "temps plein", "préavis"],
        },
        {
            "id": "fr-ecole",
            "title": "École & Crèche",
            "artist": "Школа · діти",
            "emoji": "🎒",
            "words": ["inscription", "maître", "crèche",
                      "maternelle", "devoirs", "cantine",
                      "bulletin", "réunion parents-profs",
                      "vacances scolaires", "carnet de liaison"],
        },
    ],
    "uk": [
        {
            "id": "uk-magazyn",
            "title": "В магазині",
            "artist": "Покупки · ціни",
            "emoji": "🛒",
            "words": ["продавець", "каса", "ціна", "знижка",
                      "черга", "здача", "пакет", "свіжий",
                      "термін придатності", "купити"],
        },
        {
            "id": "uk-likar",
            "title": "У лікаря",
            "artist": "Здоровʼя · ліки",
            "emoji": "🩺",
            "words": ["лікар", "запис на прийом", "симптом", "біль",
                      "ліки", "рецепт", "алергія", "температура",
                      "страховка", "швидка допомога"],
        },
        {
            "id": "uk-transport",
            "title": "Транспорт",
            "artist": "Маршрутки · метро",
            "emoji": "🚌",
            "words": ["автобус", "метро", "трамвай", "зупинка",
                      "квиток", "маршрут", "пересадка",
                      "проїзний", "розклад", "запізнюватись"],
        },
        {
            "id": "uk-hotel",
            "title": "Готель",
            "artist": "Бронювання · поселення",
            "emoji": "🏨",
            "words": ["готель", "бронювання", "номер", "ключ",
                      "адміністратор", "сніданок", "вільний номер",
                      "виселення", "депозит", "скарга"],
        },
        {
            "id": "uk-bank",
            "title": "Банк",
            "artist": "Картка · переказ",
            "emoji": "🏦",
            "words": ["рахунок", "карта", "зняти гроші",
                      "поповнити рахунок", "баланс", "комісія",
                      "переказ", "банкомат", "кредит", "виписка"],
        },
        {
            "id": "uk-znayomstvo",
            "title": "Знайомство",
            "artist": "Перші слова",
            "emoji": "👋",
            "words": ["привіт", "як справи", "мене звати",
                      "приємно познайомитись", "звідки ти",
                      "чим займаєшся", "скільки років",
                      "одружений", "разом", "зустрітись"],
        },
    ],
}


def get_theme_packs(target_lang: str) -> list:
    return [{"category": "theme", **p} for p in THEME_PACKS.get(target_lang, [])]


def get_theme_pack(target_lang: str, pack_id: str) -> dict | None:
    for p in THEME_PACKS.get(target_lang, []):
        if p["id"] == pack_id:
            return {"category": "theme", **p}
    return None
